// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: scmp/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's address (e.g. "alice@example.com").
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Authentication method.
	//
	// Types that are valid to be assigned to Credential:
	//
	//	*AuthenticateRequest_Password
	//	*AuthenticateRequest_ClientCert
	Credential    isAuthenticateRequest_Credential `protobuf_oneof:"credential"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_scmp_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AuthenticateRequest) GetCredential() isAuthenticateRequest_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *AuthenticateRequest) GetPassword() *PasswordCredential {
	if x != nil {
		if x, ok := x.Credential.(*AuthenticateRequest_Password); ok {
			return x.Password
		}
	}
	return nil
}

func (x *AuthenticateRequest) GetClientCert() *ClientCertCredential {
	if x != nil {
		if x, ok := x.Credential.(*AuthenticateRequest_ClientCert); ok {
			return x.ClientCert
		}
	}
	return nil
}

type isAuthenticateRequest_Credential interface {
	isAuthenticateRequest_Credential()
}

type AuthenticateRequest_Password struct {
	Password *PasswordCredential `protobuf:"bytes,2,opt,name=password,proto3,oneof"`
}

type AuthenticateRequest_ClientCert struct {
	ClientCert *ClientCertCredential `protobuf:"bytes,3,opt,name=client_cert,json=clientCert,proto3,oneof"`
}

func (*AuthenticateRequest_Password) isAuthenticateRequest_Credential() {}

func (*AuthenticateRequest_ClientCert) isAuthenticateRequest_Credential() {}

type PasswordCredential struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Password string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	// Optional TOTP or hardware key second factor.
	SecondFactor  string `protobuf:"bytes,2,opt,name=second_factor,json=secondFactor,proto3" json:"second_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordCredential) Reset() {
	*x = PasswordCredential{}
	mi := &file_scmp_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordCredential) ProtoMessage() {}

func (x *PasswordCredential) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordCredential.ProtoReflect.Descriptor instead.
func (*PasswordCredential) Descriptor() ([]byte, []int) {
	return file_scmp_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *PasswordCredential) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PasswordCredential) GetSecondFactor() string {
	if x != nil {
		return x.SecondFactor
	}
	return ""
}

type ClientCertCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCertCredential) Reset() {
	*x = ClientCertCredential{}
	mi := &file_scmp_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCertCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCertCredential) ProtoMessage() {}

func (x *ClientCertCredential) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCertCredential.ProtoReflect.Descriptor instead.
func (*ClientCertCredential) Descriptor() ([]byte, []int) {
	return file_scmp_v1_auth_proto_rawDescGZIP(), []int{2}
}

type AuthenticateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session token for subsequent requests.
	SessionToken string `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	// Session expiry (Unix seconds).
	ExpiresAt int64 `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Server capabilities advertised at auth time.
	Capabilities  []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_scmp_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticateResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthenticateResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AuthenticateResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_scmp_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_auth_proto_rawDescGZIP(), []int{4}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_scmp_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_auth_proto_rawDescGZIP(), []int{5}
}

var File_scmp_v1_auth_proto protoreflect.FileDescriptor

const file_scmp_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12scmp/v1/auth.proto\x12\ascmp.v1\"\xba\x01\n" +
	"\x13AuthenticateRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x129\n" +
	"\bpassword\x18\x02 \x01(\v2\x1b.scmp.v1.PasswordCredentialH\x00R\bpassword\x12@\n" +
	"\vclient_cert\x18\x03 \x01(\v2\x1d.scmp.v1.ClientCertCredentialH\x00R\n" +
	"clientCertB\f\n" +
	"\n" +
	"credential\"U\n" +
	"\x12PasswordCredential\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12#\n" +
	"\rsecond_factor\x18\x02 \x01(\tR\fsecondFactor\"\x16\n" +
	"\x14ClientCertCredential\"~\n" +
	"\x14AuthenticateResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse2\x95\x01\n" +
	"\vAuthService\x12K\n" +
	"\fAuthenticate\x12\x1c.scmp.v1.AuthenticateRequest\x1a\x1d.scmp.v1.AuthenticateResponse\x129\n" +
	"\x06Logout\x12\x16.scmp.v1.LogoutRequest\x1a\x17.scmp.v1.LogoutResponseB*Z(github.com/infodancer/scmp/proto/scmp/v1b\x06proto3"

var (
	file_scmp_v1_auth_proto_rawDescOnce sync.Once
	file_scmp_v1_auth_proto_rawDescData []byte
)

func file_scmp_v1_auth_proto_rawDescGZIP() []byte {
	file_scmp_v1_auth_proto_rawDescOnce.Do(func() {
		file_scmp_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scmp_v1_auth_proto_rawDesc), len(file_scmp_v1_auth_proto_rawDesc)))
	})
	return file_scmp_v1_auth_proto_rawDescData
}

var file_scmp_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_scmp_v1_auth_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),  // 0: scmp.v1.AuthenticateRequest
	(*PasswordCredential)(nil),   // 1: scmp.v1.PasswordCredential
	(*ClientCertCredential)(nil), // 2: scmp.v1.ClientCertCredential
	(*AuthenticateResponse)(nil), // 3: scmp.v1.AuthenticateResponse
	(*LogoutRequest)(nil),        // 4: scmp.v1.LogoutRequest
	(*LogoutResponse)(nil),       // 5: scmp.v1.LogoutResponse
}
var file_scmp_v1_auth_proto_depIdxs = []int32{
	1, // 0: scmp.v1.AuthenticateRequest.password:type_name -> scmp.v1.PasswordCredential
	2, // 1: scmp.v1.AuthenticateRequest.client_cert:type_name -> scmp.v1.ClientCertCredential
	0, // 2: scmp.v1.AuthService.Authenticate:input_type -> scmp.v1.AuthenticateRequest
	4, // 3: scmp.v1.AuthService.Logout:input_type -> scmp.v1.LogoutRequest
	3, // 4: scmp.v1.AuthService.Authenticate:output_type -> scmp.v1.AuthenticateResponse
	5, // 5: scmp.v1.AuthService.Logout:output_type -> scmp.v1.LogoutResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scmp_v1_auth_proto_init() }
func file_scmp_v1_auth_proto_init() {
	if File_scmp_v1_auth_proto != nil {
		return
	}
	file_scmp_v1_auth_proto_msgTypes[0].OneofWrappers = []any{
		(*AuthenticateRequest_Password)(nil),
		(*AuthenticateRequest_ClientCert)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scmp_v1_auth_proto_rawDesc), len(file_scmp_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scmp_v1_auth_proto_goTypes,
		DependencyIndexes: file_scmp_v1_auth_proto_depIdxs,
		MessageInfos:      file_scmp_v1_auth_proto_msgTypes,
	}.Build()
	File_scmp_v1_auth_proto = out.File
	file_scmp_v1_auth_proto_goTypes = nil
	file_scmp_v1_auth_proto_depIdxs = nil
}
