// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: scmp/v1/folders.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFoldersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoldersRequest) Reset() {
	*x = ListFoldersRequest{}
	mi := &file_scmp_v1_folders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoldersRequest) ProtoMessage() {}

func (x *ListFoldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_folders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoldersRequest.ProtoReflect.Descriptor instead.
func (*ListFoldersRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_folders_proto_rawDescGZIP(), []int{0}
}

type ListFoldersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []*Folder              `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoldersResponse) Reset() {
	*x = ListFoldersResponse{}
	mi := &file_scmp_v1_folders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoldersResponse) ProtoMessage() {}

func (x *ListFoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_folders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoldersResponse.ProtoReflect.Descriptor instead.
func (*ListFoldersResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_folders_proto_rawDescGZIP(), []int{1}
}

func (x *ListFoldersResponse) GetFolders() []*Folder {
	if x != nil {
		return x.Folders
	}
	return nil
}

type Folder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Folder name (e.g. "inbox", "sent", "drafts", "archive/2026").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Parent folder name. Empty for top-level folders.
	Parent string `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	// Total message count in this folder.
	MessageCount uint64 `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	// Unread message count.
	UnreadCount   uint64 `protobuf:"varint,4,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_scmp_v1_folders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_folders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_scmp_v1_folders_proto_rawDescGZIP(), []int{2}
}

func (x *Folder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Folder) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Folder) GetMessageCount() uint64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *Folder) GetUnreadCount() uint64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type CreateFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parent        string                 `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderRequest) Reset() {
	*x = CreateFolderRequest{}
	mi := &file_scmp_v1_folders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderRequest) ProtoMessage() {}

func (x *CreateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_folders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderRequest.ProtoReflect.Descriptor instead.
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_folders_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFolderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFolderRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type CreateFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        *Folder                `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderResponse) Reset() {
	*x = CreateFolderResponse{}
	mi := &file_scmp_v1_folders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderResponse) ProtoMessage() {}

func (x *CreateFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_folders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderResponse.ProtoReflect.Descriptor instead.
func (*CreateFolderResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_folders_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFolderResponse) GetFolder() *Folder {
	if x != nil {
		return x.Folder
	}
	return nil
}

type DeleteFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFolderRequest) Reset() {
	*x = DeleteFolderRequest{}
	mi := &file_scmp_v1_folders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFolderRequest) ProtoMessage() {}

func (x *DeleteFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_folders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFolderRequest.ProtoReflect.Descriptor instead.
func (*DeleteFolderRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_folders_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFolderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFolderResponse) Reset() {
	*x = DeleteFolderResponse{}
	mi := &file_scmp_v1_folders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFolderResponse) ProtoMessage() {}

func (x *DeleteFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_folders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFolderResponse.ProtoReflect.Descriptor instead.
func (*DeleteFolderResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_folders_proto_rawDescGZIP(), []int{6}
}

type RenameFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldName       string                 `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFolderRequest) Reset() {
	*x = RenameFolderRequest{}
	mi := &file_scmp_v1_folders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFolderRequest) ProtoMessage() {}

func (x *RenameFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_folders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFolderRequest.ProtoReflect.Descriptor instead.
func (*RenameFolderRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_folders_proto_rawDescGZIP(), []int{7}
}

func (x *RenameFolderRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameFolderRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        *Folder                `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFolderResponse) Reset() {
	*x = RenameFolderResponse{}
	mi := &file_scmp_v1_folders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFolderResponse) ProtoMessage() {}

func (x *RenameFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_folders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFolderResponse.ProtoReflect.Descriptor instead.
func (*RenameFolderResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_folders_proto_rawDescGZIP(), []int{8}
}

func (x *RenameFolderResponse) GetFolder() *Folder {
	if x != nil {
		return x.Folder
	}
	return nil
}

type MoveMessageRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MessageId         []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	DestinationFolder string                 `protobuf:"bytes,2,opt,name=destination_folder,json=destinationFolder,proto3" json:"destination_folder,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MoveMessageRequest) Reset() {
	*x = MoveMessageRequest{}
	mi := &file_scmp_v1_folders_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveMessageRequest) ProtoMessage() {}

func (x *MoveMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_folders_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveMessageRequest.ProtoReflect.Descriptor instead.
func (*MoveMessageRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_folders_proto_rawDescGZIP(), []int{9}
}

func (x *MoveMessageRequest) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MoveMessageRequest) GetDestinationFolder() string {
	if x != nil {
		return x.DestinationFolder
	}
	return ""
}

type MoveMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveMessageResponse) Reset() {
	*x = MoveMessageResponse{}
	mi := &file_scmp_v1_folders_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveMessageResponse) ProtoMessage() {}

func (x *MoveMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_folders_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveMessageResponse.ProtoReflect.Descriptor instead.
func (*MoveMessageResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_folders_proto_rawDescGZIP(), []int{10}
}

var File_scmp_v1_folders_proto protoreflect.FileDescriptor

const file_scmp_v1_folders_proto_rawDesc = "" +
	"\n" +
	"\x15scmp/v1/folders.proto\x12\ascmp.v1\"\x14\n" +
	"\x12ListFoldersRequest\"@\n" +
	"\x13ListFoldersResponse\x12)\n" +
	"\afolders\x18\x01 \x03(\v2\x0f.scmp.v1.FolderR\afolders\"|\n" +
	"\x06Folder\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\tR\x06parent\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x04R\fmessageCount\x12!\n" +
	"\funread_count\x18\x04 \x01(\x04R\vunreadCount\"A\n" +
	"\x13CreateFolderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\tR\x06parent\"?\n" +
	"\x14CreateFolderResponse\x12'\n" +
	"\x06folder\x18\x01 \x01(\v2\x0f.scmp.v1.FolderR\x06folder\")\n" +
	"\x13DeleteFolderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14DeleteFolderResponse\"K\n" +
	"\x13RenameFolderRequest\x12\x19\n" +
	"\bold_name\x18\x01 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"?\n" +
	"\x14RenameFolderResponse\x12'\n" +
	"\x06folder\x18\x01 \x01(\v2\x0f.scmp.v1.FolderR\x06folder\"b\n" +
	"\x12MoveMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12-\n" +
	"\x12destination_folder\x18\x02 \x01(\tR\x11destinationFolder\"\x15\n" +
	"\x13MoveMessageResponse2\x8a\x03\n" +
	"\rFolderService\x12H\n" +
	"\vListFolders\x12\x1b.scmp.v1.ListFoldersRequest\x1a\x1c.scmp.v1.ListFoldersResponse\x12K\n" +
	"\fCreateFolder\x12\x1c.scmp.v1.CreateFolderRequest\x1a\x1d.scmp.v1.CreateFolderResponse\x12K\n" +
	"\fDeleteFolder\x12\x1c.scmp.v1.DeleteFolderRequest\x1a\x1d.scmp.v1.DeleteFolderResponse\x12K\n" +
	"\fRenameFolder\x12\x1c.scmp.v1.RenameFolderRequest\x1a\x1d.scmp.v1.RenameFolderResponse\x12H\n" +
	"\vMoveMessage\x12\x1b.scmp.v1.MoveMessageRequest\x1a\x1c.scmp.v1.MoveMessageResponseB*Z(github.com/infodancer/scmp/proto/scmp/v1b\x06proto3"

var (
	file_scmp_v1_folders_proto_rawDescOnce sync.Once
	file_scmp_v1_folders_proto_rawDescData []byte
)

func file_scmp_v1_folders_proto_rawDescGZIP() []byte {
	file_scmp_v1_folders_proto_rawDescOnce.Do(func() {
		file_scmp_v1_folders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scmp_v1_folders_proto_rawDesc), len(file_scmp_v1_folders_proto_rawDesc)))
	})
	return file_scmp_v1_folders_proto_rawDescData
}

var file_scmp_v1_folders_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_scmp_v1_folders_proto_goTypes = []any{
	(*ListFoldersRequest)(nil),   // 0: scmp.v1.ListFoldersRequest
	(*ListFoldersResponse)(nil),  // 1: scmp.v1.ListFoldersResponse
	(*Folder)(nil),               // 2: scmp.v1.Folder
	(*CreateFolderRequest)(nil),  // 3: scmp.v1.CreateFolderRequest
	(*CreateFolderResponse)(nil), // 4: scmp.v1.CreateFolderResponse
	(*DeleteFolderRequest)(nil),  // 5: scmp.v1.DeleteFolderRequest
	(*DeleteFolderResponse)(nil), // 6: scmp.v1.DeleteFolderResponse
	(*RenameFolderRequest)(nil),  // 7: scmp.v1.RenameFolderRequest
	(*RenameFolderResponse)(nil), // 8: scmp.v1.RenameFolderResponse
	(*MoveMessageRequest)(nil),   // 9: scmp.v1.MoveMessageRequest
	(*MoveMessageResponse)(nil),  // 10: scmp.v1.MoveMessageResponse
}
var file_scmp_v1_folders_proto_depIdxs = []int32{
	2,  // 0: scmp.v1.ListFoldersResponse.folders:type_name -> scmp.v1.Folder
	2,  // 1: scmp.v1.CreateFolderResponse.folder:type_name -> scmp.v1.Folder
	2,  // 2: scmp.v1.RenameFolderResponse.folder:type_name -> scmp.v1.Folder
	0,  // 3: scmp.v1.FolderService.ListFolders:input_type -> scmp.v1.ListFoldersRequest
	3,  // 4: scmp.v1.FolderService.CreateFolder:input_type -> scmp.v1.CreateFolderRequest
	5,  // 5: scmp.v1.FolderService.DeleteFolder:input_type -> scmp.v1.DeleteFolderRequest
	7,  // 6: scmp.v1.FolderService.RenameFolder:input_type -> scmp.v1.RenameFolderRequest
	9,  // 7: scmp.v1.FolderService.MoveMessage:input_type -> scmp.v1.MoveMessageRequest
	1,  // 8: scmp.v1.FolderService.ListFolders:output_type -> scmp.v1.ListFoldersResponse
	4,  // 9: scmp.v1.FolderService.CreateFolder:output_type -> scmp.v1.CreateFolderResponse
	6,  // 10: scmp.v1.FolderService.DeleteFolder:output_type -> scmp.v1.DeleteFolderResponse
	8,  // 11: scmp.v1.FolderService.RenameFolder:output_type -> scmp.v1.RenameFolderResponse
	10, // 12: scmp.v1.FolderService.MoveMessage:output_type -> scmp.v1.MoveMessageResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_scmp_v1_folders_proto_init() }
func file_scmp_v1_folders_proto_init() {
	if File_scmp_v1_folders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scmp_v1_folders_proto_rawDesc), len(file_scmp_v1_folders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scmp_v1_folders_proto_goTypes,
		DependencyIndexes: file_scmp_v1_folders_proto_depIdxs,
		MessageInfos:      file_scmp_v1_folders_proto_msgTypes,
	}.Build()
	File_scmp_v1_folders_proto = out.File
	file_scmp_v1_folders_proto_goTypes = nil
	file_scmp_v1_folders_proto_depIdxs = nil
}
