// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: scmp/v1/keys.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyService_SubmitPublicKey_FullMethodName    = "/scmp.v1.KeyService/SubmitPublicKey"
	KeyService_GetSignedKey_FullMethodName       = "/scmp.v1.KeyService/GetSignedKey"
	KeyService_RotateKey_FullMethodName          = "/scmp.v1.KeyService/RotateKey"
	KeyService_RevokeKey_FullMethodName          = "/scmp.v1.KeyService/RevokeKey"
	KeyService_LookupKey_FullMethodName          = "/scmp.v1.KeyService/LookupKey"
	KeyService_MonitorFingerprint_FullMethodName = "/scmp.v1.KeyService/MonitorFingerprint"
)

// KeyServiceClient is the client API for KeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KeyService handles user key management through the C2S interface.
// Users generate their own private keys and submit public keys for
// domain signing. Domains MAY generate and escrow keys for non-technical
// users, but SHOULD allow user-generated keys.
type KeyServiceClient interface {
	// SubmitPublicKey submits a user-generated public key for domain signing.
	// The domain signs the key, asserting "this key belongs to this user at
	// this domain."
	SubmitPublicKey(ctx context.Context, in *SubmitPublicKeyRequest, opts ...grpc.CallOption) (*SubmitPublicKeyResponse, error)
	// GetSignedKey retrieves the user's domain-signed key for distribution.
	GetSignedKey(ctx context.Context, in *GetSignedKeyRequest, opts ...grpc.CallOption) (*GetSignedKeyResponse, error)
	// RotateKey performs atomic key rotation: revokes the old key and
	// publishes a new one. Timestamped and auditable. Triggers change
	// notifications at all correspondent caches.
	RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*RotateKeyResponse, error)
	// RevokeKey publishes a revocation for the current key without
	// submitting a replacement.
	RevokeKey(ctx context.Context, in *RevokeKeyRequest, opts ...grpc.CallOption) (*RevokeKeyResponse, error)
	// LookupKey retrieves another user's signed key (inbound key discovery).
	// The server fetches from the target domain's KeyService via SDMP.
	LookupKey(ctx context.Context, in *LookupKeyRequest, opts ...grpc.CallOption) (*LookupKeyResponse, error)
	// MonitorFingerprint checks the user's own published fingerprint.
	// Alerts immediately if the domain changed it without user action.
	// The user's client is their canary.
	MonitorFingerprint(ctx context.Context, in *MonitorFingerprintRequest, opts ...grpc.CallOption) (*MonitorFingerprintResponse, error)
}

type keyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyServiceClient(cc grpc.ClientConnInterface) KeyServiceClient {
	return &keyServiceClient{cc}
}

func (c *keyServiceClient) SubmitPublicKey(ctx context.Context, in *SubmitPublicKeyRequest, opts ...grpc.CallOption) (*SubmitPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitPublicKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_SubmitPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) GetSignedKey(ctx context.Context, in *GetSignedKeyRequest, opts ...grpc.CallOption) (*GetSignedKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSignedKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_GetSignedKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*RotateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_RotateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RevokeKey(ctx context.Context, in *RevokeKeyRequest, opts ...grpc.CallOption) (*RevokeKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_RevokeKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) LookupKey(ctx context.Context, in *LookupKeyRequest, opts ...grpc.CallOption) (*LookupKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_LookupKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) MonitorFingerprint(ctx context.Context, in *MonitorFingerprintRequest, opts ...grpc.CallOption) (*MonitorFingerprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorFingerprintResponse)
	err := c.cc.Invoke(ctx, KeyService_MonitorFingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyServiceServer is the server API for KeyService service.
// All implementations must embed UnimplementedKeyServiceServer
// for forward compatibility.
//
// KeyService handles user key management through the C2S interface.
// Users generate their own private keys and submit public keys for
// domain signing. Domains MAY generate and escrow keys for non-technical
// users, but SHOULD allow user-generated keys.
type KeyServiceServer interface {
	// SubmitPublicKey submits a user-generated public key for domain signing.
	// The domain signs the key, asserting "this key belongs to this user at
	// this domain."
	SubmitPublicKey(context.Context, *SubmitPublicKeyRequest) (*SubmitPublicKeyResponse, error)
	// GetSignedKey retrieves the user's domain-signed key for distribution.
	GetSignedKey(context.Context, *GetSignedKeyRequest) (*GetSignedKeyResponse, error)
	// RotateKey performs atomic key rotation: revokes the old key and
	// publishes a new one. Timestamped and auditable. Triggers change
	// notifications at all correspondent caches.
	RotateKey(context.Context, *RotateKeyRequest) (*RotateKeyResponse, error)
	// RevokeKey publishes a revocation for the current key without
	// submitting a replacement.
	RevokeKey(context.Context, *RevokeKeyRequest) (*RevokeKeyResponse, error)
	// LookupKey retrieves another user's signed key (inbound key discovery).
	// The server fetches from the target domain's KeyService via SDMP.
	LookupKey(context.Context, *LookupKeyRequest) (*LookupKeyResponse, error)
	// MonitorFingerprint checks the user's own published fingerprint.
	// Alerts immediately if the domain changed it without user action.
	// The user's client is their canary.
	MonitorFingerprint(context.Context, *MonitorFingerprintRequest) (*MonitorFingerprintResponse, error)
	mustEmbedUnimplementedKeyServiceServer()
}

// UnimplementedKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyServiceServer struct{}

func (UnimplementedKeyServiceServer) SubmitPublicKey(context.Context, *SubmitPublicKeyRequest) (*SubmitPublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitPublicKey not implemented")
}
func (UnimplementedKeyServiceServer) GetSignedKey(context.Context, *GetSignedKeyRequest) (*GetSignedKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSignedKey not implemented")
}
func (UnimplementedKeyServiceServer) RotateKey(context.Context, *RotateKeyRequest) (*RotateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateKey not implemented")
}
func (UnimplementedKeyServiceServer) RevokeKey(context.Context, *RevokeKeyRequest) (*RevokeKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeKey not implemented")
}
func (UnimplementedKeyServiceServer) LookupKey(context.Context, *LookupKeyRequest) (*LookupKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupKey not implemented")
}
func (UnimplementedKeyServiceServer) MonitorFingerprint(context.Context, *MonitorFingerprintRequest) (*MonitorFingerprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MonitorFingerprint not implemented")
}
func (UnimplementedKeyServiceServer) mustEmbedUnimplementedKeyServiceServer() {}
func (UnimplementedKeyServiceServer) testEmbeddedByValue()                    {}

// UnsafeKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyServiceServer will
// result in compilation errors.
type UnsafeKeyServiceServer interface {
	mustEmbedUnimplementedKeyServiceServer()
}

func RegisterKeyServiceServer(s grpc.ServiceRegistrar, srv KeyServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyService_ServiceDesc, srv)
}

func _KeyService_SubmitPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).SubmitPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_SubmitPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).SubmitPublicKey(ctx, req.(*SubmitPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_GetSignedKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignedKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).GetSignedKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_GetSignedKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).GetSignedKey(ctx, req.(*GetSignedKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RotateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RotateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_RotateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RotateKey(ctx, req.(*RotateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RevokeKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RevokeKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_RevokeKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RevokeKey(ctx, req.(*RevokeKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_LookupKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).LookupKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_LookupKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).LookupKey(ctx, req.(*LookupKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_MonitorFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorFingerprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).MonitorFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_MonitorFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).MonitorFingerprint(ctx, req.(*MonitorFingerprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyService_ServiceDesc is the grpc.ServiceDesc for KeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scmp.v1.KeyService",
	HandlerType: (*KeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitPublicKey",
			Handler:    _KeyService_SubmitPublicKey_Handler,
		},
		{
			MethodName: "GetSignedKey",
			Handler:    _KeyService_GetSignedKey_Handler,
		},
		{
			MethodName: "RotateKey",
			Handler:    _KeyService_RotateKey_Handler,
		},
		{
			MethodName: "RevokeKey",
			Handler:    _KeyService_RevokeKey_Handler,
		},
		{
			MethodName: "LookupKey",
			Handler:    _KeyService_LookupKey_Handler,
		},
		{
			MethodName: "MonitorFingerprint",
			Handler:    _KeyService_MonitorFingerprint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scmp/v1/keys.proto",
}
