// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: scmp/v1/keys.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitPublicKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public key algorithm (e.g. "Ed25519", "X25519").
	Algorithm string `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// Public key material.
	PublicKey     []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPublicKeyRequest) Reset() {
	*x = SubmitPublicKeyRequest{}
	mi := &file_scmp_v1_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPublicKeyRequest) ProtoMessage() {}

func (x *SubmitPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*SubmitPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_keys_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitPublicKeyRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *SubmitPublicKeyRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type SubmitPublicKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The domain-signed key record.
	Fingerprint     []byte `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	DomainSignature []byte `protobuf:"bytes,2,opt,name=domain_signature,json=domainSignature,proto3" json:"domain_signature,omitempty"`
	ValidFrom       int64  `protobuf:"varint,3,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidUntil      int64  `protobuf:"varint,4,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitPublicKeyResponse) Reset() {
	*x = SubmitPublicKeyResponse{}
	mi := &file_scmp_v1_keys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPublicKeyResponse) ProtoMessage() {}

func (x *SubmitPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_keys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*SubmitPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_keys_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitPublicKeyResponse) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *SubmitPublicKeyResponse) GetDomainSignature() []byte {
	if x != nil {
		return x.DomainSignature
	}
	return nil
}

func (x *SubmitPublicKeyResponse) GetValidFrom() int64 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *SubmitPublicKeyResponse) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

type GetSignedKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignedKeyRequest) Reset() {
	*x = GetSignedKeyRequest{}
	mi := &file_scmp_v1_keys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignedKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignedKeyRequest) ProtoMessage() {}

func (x *GetSignedKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_keys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignedKeyRequest.ProtoReflect.Descriptor instead.
func (*GetSignedKeyRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_keys_proto_rawDescGZIP(), []int{2}
}

type GetSignedKeyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Algorithm       string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	PublicKey       []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Fingerprint     []byte                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	ValidFrom       int64                  `protobuf:"varint,4,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidUntil      int64                  `protobuf:"varint,5,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	Escrowed        bool                   `protobuf:"varint,6,opt,name=escrowed,proto3" json:"escrowed,omitempty"`
	DomainSignature []byte                 `protobuf:"bytes,7,opt,name=domain_signature,json=domainSignature,proto3" json:"domain_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSignedKeyResponse) Reset() {
	*x = GetSignedKeyResponse{}
	mi := &file_scmp_v1_keys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignedKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignedKeyResponse) ProtoMessage() {}

func (x *GetSignedKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_keys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignedKeyResponse.ProtoReflect.Descriptor instead.
func (*GetSignedKeyResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_keys_proto_rawDescGZIP(), []int{3}
}

func (x *GetSignedKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *GetSignedKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *GetSignedKeyResponse) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *GetSignedKeyResponse) GetValidFrom() int64 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *GetSignedKeyResponse) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

func (x *GetSignedKeyResponse) GetEscrowed() bool {
	if x != nil {
		return x.Escrowed
	}
	return false
}

func (x *GetSignedKeyResponse) GetDomainSignature() []byte {
	if x != nil {
		return x.DomainSignature
	}
	return nil
}

type RotateKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New public key material.
	Algorithm     string `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	NewPublicKey  []byte `protobuf:"bytes,2,opt,name=new_public_key,json=newPublicKey,proto3" json:"new_public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeyRequest) Reset() {
	*x = RotateKeyRequest{}
	mi := &file_scmp_v1_keys_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeyRequest) ProtoMessage() {}

func (x *RotateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_keys_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateKeyRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_keys_proto_rawDescGZIP(), []int{4}
}

func (x *RotateKeyRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *RotateKeyRequest) GetNewPublicKey() []byte {
	if x != nil {
		return x.NewPublicKey
	}
	return nil
}

type RotateKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New key fingerprint after rotation.
	NewFingerprint  []byte `protobuf:"bytes,1,opt,name=new_fingerprint,json=newFingerprint,proto3" json:"new_fingerprint,omitempty"`
	DomainSignature []byte `protobuf:"bytes,2,opt,name=domain_signature,json=domainSignature,proto3" json:"domain_signature,omitempty"`
	ValidFrom       int64  `protobuf:"varint,3,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidUntil      int64  `protobuf:"varint,4,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RotateKeyResponse) Reset() {
	*x = RotateKeyResponse{}
	mi := &file_scmp_v1_keys_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeyResponse) ProtoMessage() {}

func (x *RotateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_keys_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateKeyResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_keys_proto_rawDescGZIP(), []int{5}
}

func (x *RotateKeyResponse) GetNewFingerprint() []byte {
	if x != nil {
		return x.NewFingerprint
	}
	return nil
}

func (x *RotateKeyResponse) GetDomainSignature() []byte {
	if x != nil {
		return x.DomainSignature
	}
	return nil
}

func (x *RotateKeyResponse) GetValidFrom() int64 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *RotateKeyResponse) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

type RevokeKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeKeyRequest) Reset() {
	*x = RevokeKeyRequest{}
	mi := &file_scmp_v1_keys_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeKeyRequest) ProtoMessage() {}

func (x *RevokeKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_keys_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeKeyRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_keys_proto_rawDescGZIP(), []int{6}
}

type RevokeKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevokedAt     int64                  `protobuf:"varint,1,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeKeyResponse) Reset() {
	*x = RevokeKeyResponse{}
	mi := &file_scmp_v1_keys_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeKeyResponse) ProtoMessage() {}

func (x *RevokeKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_keys_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeKeyResponse.ProtoReflect.Descriptor instead.
func (*RevokeKeyResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_keys_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeKeyResponse) GetRevokedAt() int64 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

type LookupKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The address to look up (e.g. "bob@example.com").
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupKeyRequest) Reset() {
	*x = LookupKeyRequest{}
	mi := &file_scmp_v1_keys_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupKeyRequest) ProtoMessage() {}

func (x *LookupKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_keys_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupKeyRequest.ProtoReflect.Descriptor instead.
func (*LookupKeyRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_keys_proto_rawDescGZIP(), []int{8}
}

func (x *LookupKeyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type LookupKeyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Address         string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Algorithm       string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	PublicKey       []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Fingerprint     []byte                 `protobuf:"bytes,4,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	ValidFrom       int64                  `protobuf:"varint,5,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidUntil      int64                  `protobuf:"varint,6,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	Revoked         bool                   `protobuf:"varint,7,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Escrowed        bool                   `protobuf:"varint,8,opt,name=escrowed,proto3" json:"escrowed,omitempty"`
	DomainSignature []byte                 `protobuf:"bytes,9,opt,name=domain_signature,json=domainSignature,proto3" json:"domain_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LookupKeyResponse) Reset() {
	*x = LookupKeyResponse{}
	mi := &file_scmp_v1_keys_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupKeyResponse) ProtoMessage() {}

func (x *LookupKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_keys_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupKeyResponse.ProtoReflect.Descriptor instead.
func (*LookupKeyResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_keys_proto_rawDescGZIP(), []int{9}
}

func (x *LookupKeyResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *LookupKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *LookupKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *LookupKeyResponse) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *LookupKeyResponse) GetValidFrom() int64 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *LookupKeyResponse) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

func (x *LookupKeyResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *LookupKeyResponse) GetEscrowed() bool {
	if x != nil {
		return x.Escrowed
	}
	return false
}

func (x *LookupKeyResponse) GetDomainSignature() []byte {
	if x != nil {
		return x.DomainSignature
	}
	return nil
}

type MonitorFingerprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorFingerprintRequest) Reset() {
	*x = MonitorFingerprintRequest{}
	mi := &file_scmp_v1_keys_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorFingerprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorFingerprintRequest) ProtoMessage() {}

func (x *MonitorFingerprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_keys_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorFingerprintRequest.ProtoReflect.Descriptor instead.
func (*MonitorFingerprintRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_keys_proto_rawDescGZIP(), []int{10}
}

type MonitorFingerprintResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fingerprint currently published by the domain.
	PublishedFingerprint []byte `protobuf:"bytes,1,opt,name=published_fingerprint,json=publishedFingerprint,proto3" json:"published_fingerprint,omitempty"`
	// Whether it matches the client's expected fingerprint.
	MatchesExpected bool `protobuf:"varint,2,opt,name=matches_expected,json=matchesExpected,proto3" json:"matches_expected,omitempty"`
	// When the published key was last modified.
	LastModified  int64 `protobuf:"varint,3,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorFingerprintResponse) Reset() {
	*x = MonitorFingerprintResponse{}
	mi := &file_scmp_v1_keys_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorFingerprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorFingerprintResponse) ProtoMessage() {}

func (x *MonitorFingerprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_keys_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorFingerprintResponse.ProtoReflect.Descriptor instead.
func (*MonitorFingerprintResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_keys_proto_rawDescGZIP(), []int{11}
}

func (x *MonitorFingerprintResponse) GetPublishedFingerprint() []byte {
	if x != nil {
		return x.PublishedFingerprint
	}
	return nil
}

func (x *MonitorFingerprintResponse) GetMatchesExpected() bool {
	if x != nil {
		return x.MatchesExpected
	}
	return false
}

func (x *MonitorFingerprintResponse) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

var File_scmp_v1_keys_proto protoreflect.FileDescriptor

const file_scmp_v1_keys_proto_rawDesc = "" +
	"\n" +
	"\x12scmp/v1/keys.proto\x12\ascmp.v1\"U\n" +
	"\x16SubmitPublicKeyRequest\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"\xa6\x01\n" +
	"\x17SubmitPublicKeyResponse\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\fR\vfingerprint\x12)\n" +
	"\x10domain_signature\x18\x02 \x01(\fR\x0fdomainSignature\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x03 \x01(\x03R\tvalidFrom\x12\x1f\n" +
	"\vvalid_until\x18\x04 \x01(\x03R\n" +
	"validUntil\"\x15\n" +
	"\x13GetSignedKeyRequest\"\xfc\x01\n" +
	"\x14GetSignedKeyResponse\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\fR\vfingerprint\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x04 \x01(\x03R\tvalidFrom\x12\x1f\n" +
	"\vvalid_until\x18\x05 \x01(\x03R\n" +
	"validUntil\x12\x1a\n" +
	"\bescrowed\x18\x06 \x01(\bR\bescrowed\x12)\n" +
	"\x10domain_signature\x18\a \x01(\fR\x0fdomainSignature\"V\n" +
	"\x10RotateKeyRequest\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12$\n" +
	"\x0enew_public_key\x18\x02 \x01(\fR\fnewPublicKey\"\xa7\x01\n" +
	"\x11RotateKeyResponse\x12'\n" +
	"\x0fnew_fingerprint\x18\x01 \x01(\fR\x0enewFingerprint\x12)\n" +
	"\x10domain_signature\x18\x02 \x01(\fR\x0fdomainSignature\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x03 \x01(\x03R\tvalidFrom\x12\x1f\n" +
	"\vvalid_until\x18\x04 \x01(\x03R\n" +
	"validUntil\"\x12\n" +
	"\x10RevokeKeyRequest\"2\n" +
	"\x11RevokeKeyResponse\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x01 \x01(\x03R\trevokedAt\",\n" +
	"\x10LookupKeyRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\xad\x02\n" +
	"\x11LookupKeyResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12 \n" +
	"\vfingerprint\x18\x04 \x01(\fR\vfingerprint\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x05 \x01(\x03R\tvalidFrom\x12\x1f\n" +
	"\vvalid_until\x18\x06 \x01(\x03R\n" +
	"validUntil\x12\x18\n" +
	"\arevoked\x18\a \x01(\bR\arevoked\x12\x1a\n" +
	"\bescrowed\x18\b \x01(\bR\bescrowed\x12)\n" +
	"\x10domain_signature\x18\t \x01(\fR\x0fdomainSignature\"\x1b\n" +
	"\x19MonitorFingerprintRequest\"\xa1\x01\n" +
	"\x1aMonitorFingerprintResponse\x123\n" +
	"\x15published_fingerprint\x18\x01 \x01(\fR\x14publishedFingerprint\x12)\n" +
	"\x10matches_expected\x18\x02 \x01(\bR\x0fmatchesExpected\x12#\n" +
	"\rlast_modified\x18\x03 \x01(\x03R\flastModified2\xda\x03\n" +
	"\n" +
	"KeyService\x12T\n" +
	"\x0fSubmitPublicKey\x12\x1f.scmp.v1.SubmitPublicKeyRequest\x1a .scmp.v1.SubmitPublicKeyResponse\x12K\n" +
	"\fGetSignedKey\x12\x1c.scmp.v1.GetSignedKeyRequest\x1a\x1d.scmp.v1.GetSignedKeyResponse\x12B\n" +
	"\tRotateKey\x12\x19.scmp.v1.RotateKeyRequest\x1a\x1a.scmp.v1.RotateKeyResponse\x12B\n" +
	"\tRevokeKey\x12\x19.scmp.v1.RevokeKeyRequest\x1a\x1a.scmp.v1.RevokeKeyResponse\x12B\n" +
	"\tLookupKey\x12\x19.scmp.v1.LookupKeyRequest\x1a\x1a.scmp.v1.LookupKeyResponse\x12]\n" +
	"\x12MonitorFingerprint\x12\".scmp.v1.MonitorFingerprintRequest\x1a#.scmp.v1.MonitorFingerprintResponseB*Z(github.com/infodancer/scmp/proto/scmp/v1b\x06proto3"

var (
	file_scmp_v1_keys_proto_rawDescOnce sync.Once
	file_scmp_v1_keys_proto_rawDescData []byte
)

func file_scmp_v1_keys_proto_rawDescGZIP() []byte {
	file_scmp_v1_keys_proto_rawDescOnce.Do(func() {
		file_scmp_v1_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scmp_v1_keys_proto_rawDesc), len(file_scmp_v1_keys_proto_rawDesc)))
	})
	return file_scmp_v1_keys_proto_rawDescData
}

var file_scmp_v1_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_scmp_v1_keys_proto_goTypes = []any{
	(*SubmitPublicKeyRequest)(nil),     // 0: scmp.v1.SubmitPublicKeyRequest
	(*SubmitPublicKeyResponse)(nil),    // 1: scmp.v1.SubmitPublicKeyResponse
	(*GetSignedKeyRequest)(nil),        // 2: scmp.v1.GetSignedKeyRequest
	(*GetSignedKeyResponse)(nil),       // 3: scmp.v1.GetSignedKeyResponse
	(*RotateKeyRequest)(nil),           // 4: scmp.v1.RotateKeyRequest
	(*RotateKeyResponse)(nil),          // 5: scmp.v1.RotateKeyResponse
	(*RevokeKeyRequest)(nil),           // 6: scmp.v1.RevokeKeyRequest
	(*RevokeKeyResponse)(nil),          // 7: scmp.v1.RevokeKeyResponse
	(*LookupKeyRequest)(nil),           // 8: scmp.v1.LookupKeyRequest
	(*LookupKeyResponse)(nil),          // 9: scmp.v1.LookupKeyResponse
	(*MonitorFingerprintRequest)(nil),  // 10: scmp.v1.MonitorFingerprintRequest
	(*MonitorFingerprintResponse)(nil), // 11: scmp.v1.MonitorFingerprintResponse
}
var file_scmp_v1_keys_proto_depIdxs = []int32{
	0,  // 0: scmp.v1.KeyService.SubmitPublicKey:input_type -> scmp.v1.SubmitPublicKeyRequest
	2,  // 1: scmp.v1.KeyService.GetSignedKey:input_type -> scmp.v1.GetSignedKeyRequest
	4,  // 2: scmp.v1.KeyService.RotateKey:input_type -> scmp.v1.RotateKeyRequest
	6,  // 3: scmp.v1.KeyService.RevokeKey:input_type -> scmp.v1.RevokeKeyRequest
	8,  // 4: scmp.v1.KeyService.LookupKey:input_type -> scmp.v1.LookupKeyRequest
	10, // 5: scmp.v1.KeyService.MonitorFingerprint:input_type -> scmp.v1.MonitorFingerprintRequest
	1,  // 6: scmp.v1.KeyService.SubmitPublicKey:output_type -> scmp.v1.SubmitPublicKeyResponse
	3,  // 7: scmp.v1.KeyService.GetSignedKey:output_type -> scmp.v1.GetSignedKeyResponse
	5,  // 8: scmp.v1.KeyService.RotateKey:output_type -> scmp.v1.RotateKeyResponse
	7,  // 9: scmp.v1.KeyService.RevokeKey:output_type -> scmp.v1.RevokeKeyResponse
	9,  // 10: scmp.v1.KeyService.LookupKey:output_type -> scmp.v1.LookupKeyResponse
	11, // 11: scmp.v1.KeyService.MonitorFingerprint:output_type -> scmp.v1.MonitorFingerprintResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_scmp_v1_keys_proto_init() }
func file_scmp_v1_keys_proto_init() {
	if File_scmp_v1_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scmp_v1_keys_proto_rawDesc), len(file_scmp_v1_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scmp_v1_keys_proto_goTypes,
		DependencyIndexes: file_scmp_v1_keys_proto_depIdxs,
		MessageInfos:      file_scmp_v1_keys_proto_msgTypes,
	}.Build()
	File_scmp_v1_keys_proto = out.File
	file_scmp_v1_keys_proto_goTypes = nil
	file_scmp_v1_keys_proto_depIdxs = nil
}
