// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: scmp/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Well-known flag bits for MessageSummary.flags.
type MessageFlag int32

const (
	MessageFlag_MESSAGE_FLAG_UNSPECIFIED MessageFlag = 0
	MessageFlag_MESSAGE_FLAG_READ        MessageFlag = 1
	MessageFlag_MESSAGE_FLAG_FLAGGED     MessageFlag = 2
	MessageFlag_MESSAGE_FLAG_ANSWERED    MessageFlag = 4
	MessageFlag_MESSAGE_FLAG_DRAFT       MessageFlag = 8
)

// Enum value maps for MessageFlag.
var (
	MessageFlag_name = map[int32]string{
		0: "MESSAGE_FLAG_UNSPECIFIED",
		1: "MESSAGE_FLAG_READ",
		2: "MESSAGE_FLAG_FLAGGED",
		4: "MESSAGE_FLAG_ANSWERED",
		8: "MESSAGE_FLAG_DRAFT",
	}
	MessageFlag_value = map[string]int32{
		"MESSAGE_FLAG_UNSPECIFIED": 0,
		"MESSAGE_FLAG_READ":        1,
		"MESSAGE_FLAG_FLAGGED":     2,
		"MESSAGE_FLAG_ANSWERED":    4,
		"MESSAGE_FLAG_DRAFT":       8,
	}
)

func (x MessageFlag) Enum() *MessageFlag {
	p := new(MessageFlag)
	*p = x
	return p
}

func (x MessageFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_scmp_v1_messages_proto_enumTypes[0].Descriptor()
}

func (MessageFlag) Type() protoreflect.EnumType {
	return &file_scmp_v1_messages_proto_enumTypes[0]
}

func (x MessageFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageFlag.Descriptor instead.
func (MessageFlag) EnumDescriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{0}
}

type SubmitMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination address (e.g. "bob@example.com").
	Destination string `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	// The serialized and signed envelope (created by the client).
	Envelope []byte `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// The encrypted payload (encrypted to recipient's public key by the client).
	EncryptedPayload []byte `protobuf:"bytes,3,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	// Per-message transit expiry (Unix seconds). Server may enforce a maximum.
	TransitExpiry int64 `protobuf:"varint,4,opt,name=transit_expiry,json=transitExpiry,proto3" json:"transit_expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMessageRequest) Reset() {
	*x = SubmitMessageRequest{}
	mi := &file_scmp_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMessageRequest) ProtoMessage() {}

func (x *SubmitMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMessageRequest.ProtoReflect.Descriptor instead.
func (*SubmitMessageRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitMessageRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SubmitMessageRequest) GetEnvelope() []byte {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *SubmitMessageRequest) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *SubmitMessageRequest) GetTransitExpiry() int64 {
	if x != nil {
		return x.TransitExpiry
	}
	return 0
}

type SubmitMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The protocol-generated message ID assigned to this message.
	MessageId []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Server-attested acceptance timestamp.
	AcceptedAt    int64 `protobuf:"varint,2,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMessageResponse) Reset() {
	*x = SubmitMessageResponse{}
	mi := &file_scmp_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMessageResponse) ProtoMessage() {}

func (x *SubmitMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMessageResponse.ProtoReflect.Descriptor instead.
func (*SubmitMessageResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitMessageResponse) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *SubmitMessageResponse) GetAcceptedAt() int64 {
	if x != nil {
		return x.AcceptedAt
	}
	return 0
}

type ListMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Folder to list (e.g. "inbox", "sent"). Empty string for default inbox.
	Folder string `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	// Pagination cursor from a previous response. Empty for first page.
	Cursor string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Maximum number of results per page.
	Limit         uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_scmp_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ListMessagesRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *ListMessagesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListMessagesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMessagesResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Messages []*MessageSummary      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// Cursor for the next page. Empty if no more results.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_scmp_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ListMessagesResponse) GetMessages() []*MessageSummary {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type MessageSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol-assigned message ID.
	MessageId []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Sender address (from envelope, verified by server).
	Sender string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Declared MIME type hint.
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Payload size in bytes.
	PayloadSize uint64 `protobuf:"varint,4,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	// Sender-attested timestamp.
	Timestamp int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Parent message ID if this is a reply.
	ThreadId []byte `protobuf:"bytes,6,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	// Message flags (read, flagged, etc.).
	Flags uint32 `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	// Folder this message belongs to.
	Folder        string `protobuf:"bytes,8,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSummary) Reset() {
	*x = MessageSummary{}
	mi := &file_scmp_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSummary) ProtoMessage() {}

func (x *MessageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSummary.ProtoReflect.Descriptor instead.
func (*MessageSummary) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *MessageSummary) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MessageSummary) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MessageSummary) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MessageSummary) GetPayloadSize() uint64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *MessageSummary) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageSummary) GetThreadId() []byte {
	if x != nil {
		return x.ThreadId
	}
	return nil
}

func (x *MessageSummary) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *MessageSummary) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type FetchMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMessageRequest) Reset() {
	*x = FetchMessageRequest{}
	mi := &file_scmp_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMessageRequest) ProtoMessage() {}

func (x *FetchMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMessageRequest.ProtoReflect.Descriptor instead.
func (*FetchMessageRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *FetchMessageRequest) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type FetchMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message envelope.
	Envelope []byte `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// The encrypted payload.
	EncryptedPayload []byte `protobuf:"bytes,2,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FetchMessageResponse) Reset() {
	*x = FetchMessageResponse{}
	mi := &file_scmp_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMessageResponse) ProtoMessage() {}

func (x *FetchMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMessageResponse.ProtoReflect.Descriptor instead.
func (*FetchMessageResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *FetchMessageResponse) GetEnvelope() []byte {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *FetchMessageResponse) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

type AcceptMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message ID to accept from transit into the user's store.
	MessageId []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Folder to deliver into. Empty string for default inbox.
	Folder        string `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptMessageRequest) Reset() {
	*x = AcceptMessageRequest{}
	mi := &file_scmp_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMessageRequest) ProtoMessage() {}

func (x *AcceptMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMessageRequest.ProtoReflect.Descriptor instead.
func (*AcceptMessageRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptMessageRequest) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *AcceptMessageRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type AcceptMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-attested acceptance timestamp.
	AcceptedAt    int64 `protobuf:"varint,1,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptMessageResponse) Reset() {
	*x = AcceptMessageResponse{}
	mi := &file_scmp_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMessageResponse) ProtoMessage() {}

func (x *AcceptMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMessageResponse.ProtoReflect.Descriptor instead.
func (*AcceptMessageResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptMessageResponse) GetAcceptedAt() int64 {
	if x != nil {
		return x.AcceptedAt
	}
	return 0
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_scmp_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMessageRequest) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_scmp_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{10}
}

type ListPendingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination cursor.
	Cursor        string `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingRequest) Reset() {
	*x = ListPendingRequest{}
	mi := &file_scmp_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingRequest) ProtoMessage() {}

func (x *ListPendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingRequest.ProtoReflect.Descriptor instead.
func (*ListPendingRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ListPendingRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListPendingRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListPendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PendingMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingResponse) Reset() {
	*x = ListPendingResponse{}
	mi := &file_scmp_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingResponse) ProtoMessage() {}

func (x *ListPendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingResponse.ProtoReflect.Descriptor instead.
func (*ListPendingResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ListPendingResponse) GetMessages() []*PendingMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListPendingResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type PendingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderDomain  string                 `protobuf:"bytes,2,opt,name=sender_domain,json=senderDomain,proto3" json:"sender_domain,omitempty"`
	MimeTypeHint  string                 `protobuf:"bytes,3,opt,name=mime_type_hint,json=mimeTypeHint,proto3" json:"mime_type_hint,omitempty"`
	PayloadSize   uint64                 `protobuf:"varint,4,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Expiry        int64                  `protobuf:"varint,6,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingMessage) Reset() {
	*x = PendingMessage{}
	mi := &file_scmp_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingMessage) ProtoMessage() {}

func (x *PendingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingMessage.ProtoReflect.Descriptor instead.
func (*PendingMessage) Descriptor() ([]byte, []int) {
	return file_scmp_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *PendingMessage) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *PendingMessage) GetSenderDomain() string {
	if x != nil {
		return x.SenderDomain
	}
	return ""
}

func (x *PendingMessage) GetMimeTypeHint() string {
	if x != nil {
		return x.MimeTypeHint
	}
	return ""
}

func (x *PendingMessage) GetPayloadSize() uint64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *PendingMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PendingMessage) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

var File_scmp_v1_messages_proto protoreflect.FileDescriptor

const file_scmp_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x16scmp/v1/messages.proto\x12\ascmp.v1\"\xa8\x01\n" +
	"\x14SubmitMessageRequest\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x1a\n" +
	"\benvelope\x18\x02 \x01(\fR\benvelope\x12+\n" +
	"\x11encrypted_payload\x18\x03 \x01(\fR\x10encryptedPayload\x12%\n" +
	"\x0etransit_expiry\x18\x04 \x01(\x03R\rtransitExpiry\"W\n" +
	"\x15SubmitMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12\x1f\n" +
	"\vaccepted_at\x18\x02 \x01(\x03R\n" +
	"acceptedAt\"[\n" +
	"\x13ListMessagesRequest\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"l\n" +
	"\x14ListMessagesResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.scmp.v1.MessageSummaryR\bmessages\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xf0\x01\n" +
	"\x0eMessageSummary\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12!\n" +
	"\fpayload_size\x18\x04 \x01(\x04R\vpayloadSize\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tthread_id\x18\x06 \x01(\fR\bthreadId\x12\x14\n" +
	"\x05flags\x18\a \x01(\rR\x05flags\x12\x16\n" +
	"\x06folder\x18\b \x01(\tR\x06folder\"4\n" +
	"\x13FetchMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\"_\n" +
	"\x14FetchMessageResponse\x12\x1a\n" +
	"\benvelope\x18\x01 \x01(\fR\benvelope\x12+\n" +
	"\x11encrypted_payload\x18\x02 \x01(\fR\x10encryptedPayload\"M\n" +
	"\x14AcceptMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12\x16\n" +
	"\x06folder\x18\x02 \x01(\tR\x06folder\"8\n" +
	"\x15AcceptMessageResponse\x12\x1f\n" +
	"\vaccepted_at\x18\x01 \x01(\x03R\n" +
	"acceptedAt\"5\n" +
	"\x14DeleteMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\"\x17\n" +
	"\x15DeleteMessageResponse\"B\n" +
	"\x12ListPendingRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"k\n" +
	"\x13ListPendingResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.scmp.v1.PendingMessageR\bmessages\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xd3\x01\n" +
	"\x0ePendingMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12#\n" +
	"\rsender_domain\x18\x02 \x01(\tR\fsenderDomain\x12$\n" +
	"\x0emime_type_hint\x18\x03 \x01(\tR\fmimeTypeHint\x12!\n" +
	"\fpayload_size\x18\x04 \x01(\x04R\vpayloadSize\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06expiry\x18\x06 \x01(\x03R\x06expiry*\x8f\x01\n" +
	"\vMessageFlag\x12\x1c\n" +
	"\x18MESSAGE_FLAG_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_FLAG_READ\x10\x01\x12\x18\n" +
	"\x14MESSAGE_FLAG_FLAGGED\x10\x02\x12\x19\n" +
	"\x15MESSAGE_FLAG_ANSWERED\x10\x04\x12\x16\n" +
	"\x12MESSAGE_FLAG_DRAFT\x10\b2\xe4\x03\n" +
	"\x0eMessageService\x12N\n" +
	"\rSubmitMessage\x12\x1d.scmp.v1.SubmitMessageRequest\x1a\x1e.scmp.v1.SubmitMessageResponse\x12K\n" +
	"\fListMessages\x12\x1c.scmp.v1.ListMessagesRequest\x1a\x1d.scmp.v1.ListMessagesResponse\x12K\n" +
	"\fFetchMessage\x12\x1c.scmp.v1.FetchMessageRequest\x1a\x1d.scmp.v1.FetchMessageResponse\x12N\n" +
	"\rAcceptMessage\x12\x1d.scmp.v1.AcceptMessageRequest\x1a\x1e.scmp.v1.AcceptMessageResponse\x12N\n" +
	"\rDeleteMessage\x12\x1d.scmp.v1.DeleteMessageRequest\x1a\x1e.scmp.v1.DeleteMessageResponse\x12H\n" +
	"\vListPending\x12\x1b.scmp.v1.ListPendingRequest\x1a\x1c.scmp.v1.ListPendingResponseB*Z(github.com/infodancer/scmp/proto/scmp/v1b\x06proto3"

var (
	file_scmp_v1_messages_proto_rawDescOnce sync.Once
	file_scmp_v1_messages_proto_rawDescData []byte
)

func file_scmp_v1_messages_proto_rawDescGZIP() []byte {
	file_scmp_v1_messages_proto_rawDescOnce.Do(func() {
		file_scmp_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scmp_v1_messages_proto_rawDesc), len(file_scmp_v1_messages_proto_rawDesc)))
	})
	return file_scmp_v1_messages_proto_rawDescData
}

var file_scmp_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scmp_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_scmp_v1_messages_proto_goTypes = []any{
	(MessageFlag)(0),              // 0: scmp.v1.MessageFlag
	(*SubmitMessageRequest)(nil),  // 1: scmp.v1.SubmitMessageRequest
	(*SubmitMessageResponse)(nil), // 2: scmp.v1.SubmitMessageResponse
	(*ListMessagesRequest)(nil),   // 3: scmp.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil),  // 4: scmp.v1.ListMessagesResponse
	(*MessageSummary)(nil),        // 5: scmp.v1.MessageSummary
	(*FetchMessageRequest)(nil),   // 6: scmp.v1.FetchMessageRequest
	(*FetchMessageResponse)(nil),  // 7: scmp.v1.FetchMessageResponse
	(*AcceptMessageRequest)(nil),  // 8: scmp.v1.AcceptMessageRequest
	(*AcceptMessageResponse)(nil), // 9: scmp.v1.AcceptMessageResponse
	(*DeleteMessageRequest)(nil),  // 10: scmp.v1.DeleteMessageRequest
	(*DeleteMessageResponse)(nil), // 11: scmp.v1.DeleteMessageResponse
	(*ListPendingRequest)(nil),    // 12: scmp.v1.ListPendingRequest
	(*ListPendingResponse)(nil),   // 13: scmp.v1.ListPendingResponse
	(*PendingMessage)(nil),        // 14: scmp.v1.PendingMessage
}
var file_scmp_v1_messages_proto_depIdxs = []int32{
	5,  // 0: scmp.v1.ListMessagesResponse.messages:type_name -> scmp.v1.MessageSummary
	14, // 1: scmp.v1.ListPendingResponse.messages:type_name -> scmp.v1.PendingMessage
	1,  // 2: scmp.v1.MessageService.SubmitMessage:input_type -> scmp.v1.SubmitMessageRequest
	3,  // 3: scmp.v1.MessageService.ListMessages:input_type -> scmp.v1.ListMessagesRequest
	6,  // 4: scmp.v1.MessageService.FetchMessage:input_type -> scmp.v1.FetchMessageRequest
	8,  // 5: scmp.v1.MessageService.AcceptMessage:input_type -> scmp.v1.AcceptMessageRequest
	10, // 6: scmp.v1.MessageService.DeleteMessage:input_type -> scmp.v1.DeleteMessageRequest
	12, // 7: scmp.v1.MessageService.ListPending:input_type -> scmp.v1.ListPendingRequest
	2,  // 8: scmp.v1.MessageService.SubmitMessage:output_type -> scmp.v1.SubmitMessageResponse
	4,  // 9: scmp.v1.MessageService.ListMessages:output_type -> scmp.v1.ListMessagesResponse
	7,  // 10: scmp.v1.MessageService.FetchMessage:output_type -> scmp.v1.FetchMessageResponse
	9,  // 11: scmp.v1.MessageService.AcceptMessage:output_type -> scmp.v1.AcceptMessageResponse
	11, // 12: scmp.v1.MessageService.DeleteMessage:output_type -> scmp.v1.DeleteMessageResponse
	13, // 13: scmp.v1.MessageService.ListPending:output_type -> scmp.v1.ListPendingResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_scmp_v1_messages_proto_init() }
func file_scmp_v1_messages_proto_init() {
	if File_scmp_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scmp_v1_messages_proto_rawDesc), len(file_scmp_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scmp_v1_messages_proto_goTypes,
		DependencyIndexes: file_scmp_v1_messages_proto_depIdxs,
		EnumInfos:         file_scmp_v1_messages_proto_enumTypes,
		MessageInfos:      file_scmp_v1_messages_proto_msgTypes,
	}.Build()
	File_scmp_v1_messages_proto = out.File
	file_scmp_v1_messages_proto_goTypes = nil
	file_scmp_v1_messages_proto_depIdxs = nil
}
