// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: scmp/v1/notifications.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerEvent is pushed from server to client.
type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_NewMessage
	//	*ServerEvent_KeyChange
	//	*ServerEvent_MessageFetched
	//	*ServerEvent_MessageExpired
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_scmp_v1_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_scmp_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetNewMessage() *NewMessageEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_NewMessage); ok {
			return x.NewMessage
		}
	}
	return nil
}

func (x *ServerEvent) GetKeyChange() *KeyChangeEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_KeyChange); ok {
			return x.KeyChange
		}
	}
	return nil
}

func (x *ServerEvent) GetMessageFetched() *MessageFetchedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_MessageFetched); ok {
			return x.MessageFetched
		}
	}
	return nil
}

func (x *ServerEvent) GetMessageExpired() *MessageExpiredEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_MessageExpired); ok {
			return x.MessageExpired
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_NewMessage struct {
	// A new message notification has arrived.
	NewMessage *NewMessageEvent `protobuf:"bytes,1,opt,name=new_message,json=newMessage,proto3,oneof"`
}

type ServerEvent_KeyChange struct {
	// A correspondent's key has changed.
	KeyChange *KeyChangeEvent `protobuf:"bytes,2,opt,name=key_change,json=keyChange,proto3,oneof"`
}

type ServerEvent_MessageFetched struct {
	// A message the user sent has been fetched by the recipient.
	MessageFetched *MessageFetchedEvent `protobuf:"bytes,3,opt,name=message_fetched,json=messageFetched,proto3,oneof"`
}

type ServerEvent_MessageExpired struct {
	// A previously sent message has expired without being fetched.
	MessageExpired *MessageExpiredEvent `protobuf:"bytes,4,opt,name=message_expired,json=messageExpired,proto3,oneof"`
}

func (*ServerEvent_NewMessage) isServerEvent_Event() {}

func (*ServerEvent_KeyChange) isServerEvent_Event() {}

func (*ServerEvent_MessageFetched) isServerEvent_Event() {}

func (*ServerEvent_MessageExpired) isServerEvent_Event() {}

type NewMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderDomain  string                 `protobuf:"bytes,2,opt,name=sender_domain,json=senderDomain,proto3" json:"sender_domain,omitempty"`
	MimeTypeHint  string                 `protobuf:"bytes,3,opt,name=mime_type_hint,json=mimeTypeHint,proto3" json:"mime_type_hint,omitempty"`
	PayloadSize   uint64                 `protobuf:"varint,4,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Expiry        int64                  `protobuf:"varint,6,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessageEvent) Reset() {
	*x = NewMessageEvent{}
	mi := &file_scmp_v1_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessageEvent) ProtoMessage() {}

func (x *NewMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessageEvent.ProtoReflect.Descriptor instead.
func (*NewMessageEvent) Descriptor() ([]byte, []int) {
	return file_scmp_v1_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *NewMessageEvent) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *NewMessageEvent) GetSenderDomain() string {
	if x != nil {
		return x.SenderDomain
	}
	return ""
}

func (x *NewMessageEvent) GetMimeTypeHint() string {
	if x != nil {
		return x.MimeTypeHint
	}
	return ""
}

func (x *NewMessageEvent) GetPayloadSize() uint64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *NewMessageEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NewMessageEvent) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type KeyChangeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The address whose key changed.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// New fingerprint.
	NewFingerprint []byte `protobuf:"bytes,2,opt,name=new_fingerprint,json=newFingerprint,proto3" json:"new_fingerprint,omitempty"`
	// Old fingerprint (for display to user).
	OldFingerprint []byte `protobuf:"bytes,3,opt,name=old_fingerprint,json=oldFingerprint,proto3" json:"old_fingerprint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyChangeEvent) Reset() {
	*x = KeyChangeEvent{}
	mi := &file_scmp_v1_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyChangeEvent) ProtoMessage() {}

func (x *KeyChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyChangeEvent.ProtoReflect.Descriptor instead.
func (*KeyChangeEvent) Descriptor() ([]byte, []int) {
	return file_scmp_v1_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *KeyChangeEvent) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *KeyChangeEvent) GetNewFingerprint() []byte {
	if x != nil {
		return x.NewFingerprint
	}
	return nil
}

func (x *KeyChangeEvent) GetOldFingerprint() []byte {
	if x != nil {
		return x.OldFingerprint
	}
	return nil
}

type MessageFetchedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A message the user sent has been fetched (delivery inference).
	MessageId     []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FetchedAt     int64  `protobuf:"varint,2,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageFetchedEvent) Reset() {
	*x = MessageFetchedEvent{}
	mi := &file_scmp_v1_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageFetchedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFetchedEvent) ProtoMessage() {}

func (x *MessageFetchedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFetchedEvent.ProtoReflect.Descriptor instead.
func (*MessageFetchedEvent) Descriptor() ([]byte, []int) {
	return file_scmp_v1_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *MessageFetchedEvent) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MessageFetchedEvent) GetFetchedAt() int64 {
	if x != nil {
		return x.FetchedAt
	}
	return 0
}

type MessageExpiredEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A message the user sent expired without being fetched (inferred failure).
	MessageId     []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ExpiredAt     int64  `protobuf:"varint,2,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageExpiredEvent) Reset() {
	*x = MessageExpiredEvent{}
	mi := &file_scmp_v1_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageExpiredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageExpiredEvent) ProtoMessage() {}

func (x *MessageExpiredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageExpiredEvent.ProtoReflect.Descriptor instead.
func (*MessageExpiredEvent) Descriptor() ([]byte, []int) {
	return file_scmp_v1_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *MessageExpiredEvent) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MessageExpiredEvent) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

// ClientEvent is sent from client to server on the same stream.
type ClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ClientEvent_Ack
	//	*ClientEvent_RegisterHashes
	Event         isClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_scmp_v1_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_scmp_v1_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *ClientEvent) GetEvent() isClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ClientEvent) GetAck() *AckEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ClientEvent) GetRegisterHashes() *RegisterHashesEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_RegisterHashes); ok {
			return x.RegisterHashes
		}
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_Ack struct {
	// Acknowledge receipt of a server event (by sequence number).
	Ack *AckEvent `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type ClientEvent_RegisterHashes struct {
	// Register hash addresses to watch for notifications.
	RegisterHashes *RegisterHashesEvent `protobuf:"bytes,2,opt,name=register_hashes,json=registerHashes,proto3,oneof"`
}

func (*ClientEvent_Ack) isClientEvent_Event() {}

func (*ClientEvent_RegisterHashes) isClientEvent_Event() {}

type AckEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequence number of the server event being acknowledged.
	Sequence      uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckEvent) Reset() {
	*x = AckEvent{}
	mi := &file_scmp_v1_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckEvent) ProtoMessage() {}

func (x *AckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckEvent.ProtoReflect.Descriptor instead.
func (*AckEvent) Descriptor() ([]byte, []int) {
	return file_scmp_v1_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *AckEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type RegisterHashesEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hash addresses to watch for incoming notifications.
	// Server stores these in the user's pending reference table.
	Hashes        [][]byte `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHashesEvent) Reset() {
	*x = RegisterHashesEvent{}
	mi := &file_scmp_v1_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHashesEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHashesEvent) ProtoMessage() {}

func (x *RegisterHashesEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHashesEvent.ProtoReflect.Descriptor instead.
func (*RegisterHashesEvent) Descriptor() ([]byte, []int) {
	return file_scmp_v1_notifications_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterHashesEvent) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

var File_scmp_v1_notifications_proto protoreflect.FileDescriptor

const file_scmp_v1_notifications_proto_rawDesc = "" +
	"\n" +
	"\x1bscmp/v1/notifications.proto\x12\ascmp.v1\"\x9f\x02\n" +
	"\vServerEvent\x12;\n" +
	"\vnew_message\x18\x01 \x01(\v2\x18.scmp.v1.NewMessageEventH\x00R\n" +
	"newMessage\x128\n" +
	"\n" +
	"key_change\x18\x02 \x01(\v2\x17.scmp.v1.KeyChangeEventH\x00R\tkeyChange\x12G\n" +
	"\x0fmessage_fetched\x18\x03 \x01(\v2\x1c.scmp.v1.MessageFetchedEventH\x00R\x0emessageFetched\x12G\n" +
	"\x0fmessage_expired\x18\x04 \x01(\v2\x1c.scmp.v1.MessageExpiredEventH\x00R\x0emessageExpiredB\a\n" +
	"\x05event\"\xd4\x01\n" +
	"\x0fNewMessageEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12#\n" +
	"\rsender_domain\x18\x02 \x01(\tR\fsenderDomain\x12$\n" +
	"\x0emime_type_hint\x18\x03 \x01(\tR\fmimeTypeHint\x12!\n" +
	"\fpayload_size\x18\x04 \x01(\x04R\vpayloadSize\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06expiry\x18\x06 \x01(\x03R\x06expiry\"|\n" +
	"\x0eKeyChangeEvent\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12'\n" +
	"\x0fnew_fingerprint\x18\x02 \x01(\fR\x0enewFingerprint\x12'\n" +
	"\x0fold_fingerprint\x18\x03 \x01(\fR\x0eoldFingerprint\"S\n" +
	"\x13MessageFetchedEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12\x1d\n" +
	"\n" +
	"fetched_at\x18\x02 \x01(\x03R\tfetchedAt\"S\n" +
	"\x13MessageExpiredEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x02 \x01(\x03R\texpiredAt\"\x86\x01\n" +
	"\vClientEvent\x12%\n" +
	"\x03ack\x18\x01 \x01(\v2\x11.scmp.v1.AckEventH\x00R\x03ack\x12G\n" +
	"\x0fregister_hashes\x18\x02 \x01(\v2\x1c.scmp.v1.RegisterHashesEventH\x00R\x0eregisterHashesB\a\n" +
	"\x05event\"&\n" +
	"\bAckEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"-\n" +
	"\x13RegisterHashesEvent\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\fR\x06hashes2R\n" +
	"\x13NotificationService\x12;\n" +
	"\tSubscribe\x12\x14.scmp.v1.ClientEvent\x1a\x14.scmp.v1.ServerEvent(\x010\x01B*Z(github.com/infodancer/scmp/proto/scmp/v1b\x06proto3"

var (
	file_scmp_v1_notifications_proto_rawDescOnce sync.Once
	file_scmp_v1_notifications_proto_rawDescData []byte
)

func file_scmp_v1_notifications_proto_rawDescGZIP() []byte {
	file_scmp_v1_notifications_proto_rawDescOnce.Do(func() {
		file_scmp_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scmp_v1_notifications_proto_rawDesc), len(file_scmp_v1_notifications_proto_rawDesc)))
	})
	return file_scmp_v1_notifications_proto_rawDescData
}

var file_scmp_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_scmp_v1_notifications_proto_goTypes = []any{
	(*ServerEvent)(nil),         // 0: scmp.v1.ServerEvent
	(*NewMessageEvent)(nil),     // 1: scmp.v1.NewMessageEvent
	(*KeyChangeEvent)(nil),      // 2: scmp.v1.KeyChangeEvent
	(*MessageFetchedEvent)(nil), // 3: scmp.v1.MessageFetchedEvent
	(*MessageExpiredEvent)(nil), // 4: scmp.v1.MessageExpiredEvent
	(*ClientEvent)(nil),         // 5: scmp.v1.ClientEvent
	(*AckEvent)(nil),            // 6: scmp.v1.AckEvent
	(*RegisterHashesEvent)(nil), // 7: scmp.v1.RegisterHashesEvent
}
var file_scmp_v1_notifications_proto_depIdxs = []int32{
	1, // 0: scmp.v1.ServerEvent.new_message:type_name -> scmp.v1.NewMessageEvent
	2, // 1: scmp.v1.ServerEvent.key_change:type_name -> scmp.v1.KeyChangeEvent
	3, // 2: scmp.v1.ServerEvent.message_fetched:type_name -> scmp.v1.MessageFetchedEvent
	4, // 3: scmp.v1.ServerEvent.message_expired:type_name -> scmp.v1.MessageExpiredEvent
	6, // 4: scmp.v1.ClientEvent.ack:type_name -> scmp.v1.AckEvent
	7, // 5: scmp.v1.ClientEvent.register_hashes:type_name -> scmp.v1.RegisterHashesEvent
	5, // 6: scmp.v1.NotificationService.Subscribe:input_type -> scmp.v1.ClientEvent
	0, // 7: scmp.v1.NotificationService.Subscribe:output_type -> scmp.v1.ServerEvent
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_scmp_v1_notifications_proto_init() }
func file_scmp_v1_notifications_proto_init() {
	if File_scmp_v1_notifications_proto != nil {
		return
	}
	file_scmp_v1_notifications_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerEvent_NewMessage)(nil),
		(*ServerEvent_KeyChange)(nil),
		(*ServerEvent_MessageFetched)(nil),
		(*ServerEvent_MessageExpired)(nil),
	}
	file_scmp_v1_notifications_proto_msgTypes[5].OneofWrappers = []any{
		(*ClientEvent_Ack)(nil),
		(*ClientEvent_RegisterHashes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scmp_v1_notifications_proto_rawDesc), len(file_scmp_v1_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scmp_v1_notifications_proto_goTypes,
		DependencyIndexes: file_scmp_v1_notifications_proto_depIdxs,
		MessageInfos:      file_scmp_v1_notifications_proto_msgTypes,
	}.Build()
	File_scmp_v1_notifications_proto = out.File
	file_scmp_v1_notifications_proto_goTypes = nil
	file_scmp_v1_notifications_proto_depIdxs = nil
}
