// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: scmp/v1/policy.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyService_SetPullPreference_FullMethodName   = "/scmp.v1.PolicyService/SetPullPreference"
	PolicyService_GetPullPreference_FullMethodName   = "/scmp.v1.PolicyService/GetPullPreference"
	PolicyService_ListPullPreferences_FullMethodName = "/scmp.v1.PolicyService/ListPullPreferences"
	PolicyService_SetDefaultPolicy_FullMethodName    = "/scmp.v1.PolicyService/SetDefaultPolicy"
	PolicyService_GetDefaultPolicy_FullMethodName    = "/scmp.v1.PolicyService/GetDefaultPolicy"
)

// PolicyServiceClient is the client API for PolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PolicyService handles per-sender pull preferences, reputation thresholds,
// and retention policies configured by the client.
type PolicyServiceClient interface {
	// SetPullPreference configures how the server handles notifications
	// from a specific sender domain.
	SetPullPreference(ctx context.Context, in *SetPullPreferenceRequest, opts ...grpc.CallOption) (*SetPullPreferenceResponse, error)
	// GetPullPreference retrieves the current pull preference for a sender domain.
	GetPullPreference(ctx context.Context, in *GetPullPreferenceRequest, opts ...grpc.CallOption) (*GetPullPreferenceResponse, error)
	// ListPullPreferences returns all configured per-sender pull preferences.
	ListPullPreferences(ctx context.Context, in *ListPullPreferencesRequest, opts ...grpc.CallOption) (*ListPullPreferencesResponse, error)
	// SetDefaultPolicy sets the default pull preference and retention policy
	// for senders without a specific override.
	SetDefaultPolicy(ctx context.Context, in *SetDefaultPolicyRequest, opts ...grpc.CallOption) (*SetDefaultPolicyResponse, error)
	// GetDefaultPolicy retrieves the current default policy.
	GetDefaultPolicy(ctx context.Context, in *GetDefaultPolicyRequest, opts ...grpc.CallOption) (*GetDefaultPolicyResponse, error)
}

type policyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyServiceClient(cc grpc.ClientConnInterface) PolicyServiceClient {
	return &policyServiceClient{cc}
}

func (c *policyServiceClient) SetPullPreference(ctx context.Context, in *SetPullPreferenceRequest, opts ...grpc.CallOption) (*SetPullPreferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPullPreferenceResponse)
	err := c.cc.Invoke(ctx, PolicyService_SetPullPreference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) GetPullPreference(ctx context.Context, in *GetPullPreferenceRequest, opts ...grpc.CallOption) (*GetPullPreferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPullPreferenceResponse)
	err := c.cc.Invoke(ctx, PolicyService_GetPullPreference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) ListPullPreferences(ctx context.Context, in *ListPullPreferencesRequest, opts ...grpc.CallOption) (*ListPullPreferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPullPreferencesResponse)
	err := c.cc.Invoke(ctx, PolicyService_ListPullPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) SetDefaultPolicy(ctx context.Context, in *SetDefaultPolicyRequest, opts ...grpc.CallOption) (*SetDefaultPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDefaultPolicyResponse)
	err := c.cc.Invoke(ctx, PolicyService_SetDefaultPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) GetDefaultPolicy(ctx context.Context, in *GetDefaultPolicyRequest, opts ...grpc.CallOption) (*GetDefaultPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDefaultPolicyResponse)
	err := c.cc.Invoke(ctx, PolicyService_GetDefaultPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyServiceServer is the server API for PolicyService service.
// All implementations must embed UnimplementedPolicyServiceServer
// for forward compatibility.
//
// PolicyService handles per-sender pull preferences, reputation thresholds,
// and retention policies configured by the client.
type PolicyServiceServer interface {
	// SetPullPreference configures how the server handles notifications
	// from a specific sender domain.
	SetPullPreference(context.Context, *SetPullPreferenceRequest) (*SetPullPreferenceResponse, error)
	// GetPullPreference retrieves the current pull preference for a sender domain.
	GetPullPreference(context.Context, *GetPullPreferenceRequest) (*GetPullPreferenceResponse, error)
	// ListPullPreferences returns all configured per-sender pull preferences.
	ListPullPreferences(context.Context, *ListPullPreferencesRequest) (*ListPullPreferencesResponse, error)
	// SetDefaultPolicy sets the default pull preference and retention policy
	// for senders without a specific override.
	SetDefaultPolicy(context.Context, *SetDefaultPolicyRequest) (*SetDefaultPolicyResponse, error)
	// GetDefaultPolicy retrieves the current default policy.
	GetDefaultPolicy(context.Context, *GetDefaultPolicyRequest) (*GetDefaultPolicyResponse, error)
	mustEmbedUnimplementedPolicyServiceServer()
}

// UnimplementedPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyServiceServer struct{}

func (UnimplementedPolicyServiceServer) SetPullPreference(context.Context, *SetPullPreferenceRequest) (*SetPullPreferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPullPreference not implemented")
}
func (UnimplementedPolicyServiceServer) GetPullPreference(context.Context, *GetPullPreferenceRequest) (*GetPullPreferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPullPreference not implemented")
}
func (UnimplementedPolicyServiceServer) ListPullPreferences(context.Context, *ListPullPreferencesRequest) (*ListPullPreferencesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPullPreferences not implemented")
}
func (UnimplementedPolicyServiceServer) SetDefaultPolicy(context.Context, *SetDefaultPolicyRequest) (*SetDefaultPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDefaultPolicy not implemented")
}
func (UnimplementedPolicyServiceServer) GetDefaultPolicy(context.Context, *GetDefaultPolicyRequest) (*GetDefaultPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefaultPolicy not implemented")
}
func (UnimplementedPolicyServiceServer) mustEmbedUnimplementedPolicyServiceServer() {}
func (UnimplementedPolicyServiceServer) testEmbeddedByValue()                       {}

// UnsafePolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServiceServer will
// result in compilation errors.
type UnsafePolicyServiceServer interface {
	mustEmbedUnimplementedPolicyServiceServer()
}

func RegisterPolicyServiceServer(s grpc.ServiceRegistrar, srv PolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyService_ServiceDesc, srv)
}

func _PolicyService_SetPullPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPullPreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).SetPullPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_SetPullPreference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).SetPullPreference(ctx, req.(*SetPullPreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_GetPullPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPullPreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).GetPullPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_GetPullPreference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).GetPullPreference(ctx, req.(*GetPullPreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_ListPullPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPullPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).ListPullPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_ListPullPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).ListPullPreferences(ctx, req.(*ListPullPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_SetDefaultPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).SetDefaultPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_SetDefaultPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).SetDefaultPolicy(ctx, req.(*SetDefaultPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_GetDefaultPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).GetDefaultPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_GetDefaultPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).GetDefaultPolicy(ctx, req.(*GetDefaultPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyService_ServiceDesc is the grpc.ServiceDesc for PolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scmp.v1.PolicyService",
	HandlerType: (*PolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetPullPreference",
			Handler:    _PolicyService_SetPullPreference_Handler,
		},
		{
			MethodName: "GetPullPreference",
			Handler:    _PolicyService_GetPullPreference_Handler,
		},
		{
			MethodName: "ListPullPreferences",
			Handler:    _PolicyService_ListPullPreferences_Handler,
		},
		{
			MethodName: "SetDefaultPolicy",
			Handler:    _PolicyService_SetDefaultPolicy_Handler,
		},
		{
			MethodName: "GetDefaultPolicy",
			Handler:    _PolicyService_GetDefaultPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scmp/v1/policy.proto",
}
