// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: scmp/v1/policy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PullPreference controls how the server handles notifications from a sender.
type PullPreference int32

const (
	// Server fetches automatically on notification.
	PullPreference_PULL_PREFERENCE_IMMEDIATE PullPreference = 0
	// Notification recorded; user or client initiates fetch. Default behavior.
	PullPreference_PULL_PREFERENCE_ON_REQUEST PullPreference = 1
	// Notification discarded without recording. Effective unsubscribe.
	// The sender cannot distinguish between ignored, undelivered, and not-yet-pulled.
	PullPreference_PULL_PREFERENCE_IGNORE PullPreference = 2
)

// Enum value maps for PullPreference.
var (
	PullPreference_name = map[int32]string{
		0: "PULL_PREFERENCE_IMMEDIATE",
		1: "PULL_PREFERENCE_ON_REQUEST",
		2: "PULL_PREFERENCE_IGNORE",
	}
	PullPreference_value = map[string]int32{
		"PULL_PREFERENCE_IMMEDIATE":  0,
		"PULL_PREFERENCE_ON_REQUEST": 1,
		"PULL_PREFERENCE_IGNORE":     2,
	}
)

func (x PullPreference) Enum() *PullPreference {
	p := new(PullPreference)
	*p = x
	return p
}

func (x PullPreference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullPreference) Descriptor() protoreflect.EnumDescriptor {
	return file_scmp_v1_policy_proto_enumTypes[0].Descriptor()
}

func (PullPreference) Type() protoreflect.EnumType {
	return &file_scmp_v1_policy_proto_enumTypes[0]
}

func (x PullPreference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullPreference.Descriptor instead.
func (PullPreference) EnumDescriptor() ([]byte, []int) {
	return file_scmp_v1_policy_proto_rawDescGZIP(), []int{0}
}

type SetPullPreferenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sender domain to configure (e.g. "example.com").
	SenderDomain string `protobuf:"bytes,1,opt,name=sender_domain,json=senderDomain,proto3" json:"sender_domain,omitempty"`
	// The pull preference to set.
	Preference    PullPreference `protobuf:"varint,2,opt,name=preference,proto3,enum=scmp.v1.PullPreference" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPullPreferenceRequest) Reset() {
	*x = SetPullPreferenceRequest{}
	mi := &file_scmp_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPullPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPullPreferenceRequest) ProtoMessage() {}

func (x *SetPullPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPullPreferenceRequest.ProtoReflect.Descriptor instead.
func (*SetPullPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *SetPullPreferenceRequest) GetSenderDomain() string {
	if x != nil {
		return x.SenderDomain
	}
	return ""
}

func (x *SetPullPreferenceRequest) GetPreference() PullPreference {
	if x != nil {
		return x.Preference
	}
	return PullPreference_PULL_PREFERENCE_IMMEDIATE
}

type SetPullPreferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPullPreferenceResponse) Reset() {
	*x = SetPullPreferenceResponse{}
	mi := &file_scmp_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPullPreferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPullPreferenceResponse) ProtoMessage() {}

func (x *SetPullPreferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPullPreferenceResponse.ProtoReflect.Descriptor instead.
func (*SetPullPreferenceResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_policy_proto_rawDescGZIP(), []int{1}
}

type GetPullPreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderDomain  string                 `protobuf:"bytes,1,opt,name=sender_domain,json=senderDomain,proto3" json:"sender_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPullPreferenceRequest) Reset() {
	*x = GetPullPreferenceRequest{}
	mi := &file_scmp_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPullPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullPreferenceRequest) ProtoMessage() {}

func (x *GetPullPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullPreferenceRequest.ProtoReflect.Descriptor instead.
func (*GetPullPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *GetPullPreferenceRequest) GetSenderDomain() string {
	if x != nil {
		return x.SenderDomain
	}
	return ""
}

type GetPullPreferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderDomain  string                 `protobuf:"bytes,1,opt,name=sender_domain,json=senderDomain,proto3" json:"sender_domain,omitempty"`
	Preference    PullPreference         `protobuf:"varint,2,opt,name=preference,proto3,enum=scmp.v1.PullPreference" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPullPreferenceResponse) Reset() {
	*x = GetPullPreferenceResponse{}
	mi := &file_scmp_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPullPreferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullPreferenceResponse) ProtoMessage() {}

func (x *GetPullPreferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullPreferenceResponse.ProtoReflect.Descriptor instead.
func (*GetPullPreferenceResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *GetPullPreferenceResponse) GetSenderDomain() string {
	if x != nil {
		return x.SenderDomain
	}
	return ""
}

func (x *GetPullPreferenceResponse) GetPreference() PullPreference {
	if x != nil {
		return x.Preference
	}
	return PullPreference_PULL_PREFERENCE_IMMEDIATE
}

type ListPullPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPullPreferencesRequest) Reset() {
	*x = ListPullPreferencesRequest{}
	mi := &file_scmp_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPullPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPullPreferencesRequest) ProtoMessage() {}

func (x *ListPullPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPullPreferencesRequest.ProtoReflect.Descriptor instead.
func (*ListPullPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_policy_proto_rawDescGZIP(), []int{4}
}

type ListPullPreferencesResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Preferences   []*GetPullPreferenceResponse `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPullPreferencesResponse) Reset() {
	*x = ListPullPreferencesResponse{}
	mi := &file_scmp_v1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPullPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPullPreferencesResponse) ProtoMessage() {}

func (x *ListPullPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPullPreferencesResponse.ProtoReflect.Descriptor instead.
func (*ListPullPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *ListPullPreferencesResponse) GetPreferences() []*GetPullPreferenceResponse {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type SetDefaultPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default pull preference for unknown senders.
	DefaultPreference PullPreference `protobuf:"varint,1,opt,name=default_preference,json=defaultPreference,proto3,enum=scmp.v1.PullPreference" json:"default_preference,omitempty"`
	// Default retention period for accepted messages (seconds). 0 = unlimited.
	RetentionSeconds int64 `protobuf:"varint,2,opt,name=retention_seconds,json=retentionSeconds,proto3" json:"retention_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetDefaultPolicyRequest) Reset() {
	*x = SetDefaultPolicyRequest{}
	mi := &file_scmp_v1_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultPolicyRequest) ProtoMessage() {}

func (x *SetDefaultPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultPolicyRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *SetDefaultPolicyRequest) GetDefaultPreference() PullPreference {
	if x != nil {
		return x.DefaultPreference
	}
	return PullPreference_PULL_PREFERENCE_IMMEDIATE
}

func (x *SetDefaultPolicyRequest) GetRetentionSeconds() int64 {
	if x != nil {
		return x.RetentionSeconds
	}
	return 0
}

type SetDefaultPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultPolicyResponse) Reset() {
	*x = SetDefaultPolicyResponse{}
	mi := &file_scmp_v1_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultPolicyResponse) ProtoMessage() {}

func (x *SetDefaultPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultPolicyResponse.ProtoReflect.Descriptor instead.
func (*SetDefaultPolicyResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_policy_proto_rawDescGZIP(), []int{7}
}

type GetDefaultPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultPolicyRequest) Reset() {
	*x = GetDefaultPolicyRequest{}
	mi := &file_scmp_v1_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultPolicyRequest) ProtoMessage() {}

func (x *GetDefaultPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetDefaultPolicyRequest) Descriptor() ([]byte, []int) {
	return file_scmp_v1_policy_proto_rawDescGZIP(), []int{8}
}

type GetDefaultPolicyResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DefaultPreference PullPreference         `protobuf:"varint,1,opt,name=default_preference,json=defaultPreference,proto3,enum=scmp.v1.PullPreference" json:"default_preference,omitempty"`
	RetentionSeconds  int64                  `protobuf:"varint,2,opt,name=retention_seconds,json=retentionSeconds,proto3" json:"retention_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetDefaultPolicyResponse) Reset() {
	*x = GetDefaultPolicyResponse{}
	mi := &file_scmp_v1_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultPolicyResponse) ProtoMessage() {}

func (x *GetDefaultPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scmp_v1_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetDefaultPolicyResponse) Descriptor() ([]byte, []int) {
	return file_scmp_v1_policy_proto_rawDescGZIP(), []int{9}
}

func (x *GetDefaultPolicyResponse) GetDefaultPreference() PullPreference {
	if x != nil {
		return x.DefaultPreference
	}
	return PullPreference_PULL_PREFERENCE_IMMEDIATE
}

func (x *GetDefaultPolicyResponse) GetRetentionSeconds() int64 {
	if x != nil {
		return x.RetentionSeconds
	}
	return 0
}

var File_scmp_v1_policy_proto protoreflect.FileDescriptor

const file_scmp_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x14scmp/v1/policy.proto\x12\ascmp.v1\"x\n" +
	"\x18SetPullPreferenceRequest\x12#\n" +
	"\rsender_domain\x18\x01 \x01(\tR\fsenderDomain\x127\n" +
	"\n" +
	"preference\x18\x02 \x01(\x0e2\x17.scmp.v1.PullPreferenceR\n" +
	"preference\"\x1b\n" +
	"\x19SetPullPreferenceResponse\"?\n" +
	"\x18GetPullPreferenceRequest\x12#\n" +
	"\rsender_domain\x18\x01 \x01(\tR\fsenderDomain\"y\n" +
	"\x19GetPullPreferenceResponse\x12#\n" +
	"\rsender_domain\x18\x01 \x01(\tR\fsenderDomain\x127\n" +
	"\n" +
	"preference\x18\x02 \x01(\x0e2\x17.scmp.v1.PullPreferenceR\n" +
	"preference\"\x1c\n" +
	"\x1aListPullPreferencesRequest\"c\n" +
	"\x1bListPullPreferencesResponse\x12D\n" +
	"\vpreferences\x18\x01 \x03(\v2\".scmp.v1.GetPullPreferenceResponseR\vpreferences\"\x8e\x01\n" +
	"\x17SetDefaultPolicyRequest\x12F\n" +
	"\x12default_preference\x18\x01 \x01(\x0e2\x17.scmp.v1.PullPreferenceR\x11defaultPreference\x12+\n" +
	"\x11retention_seconds\x18\x02 \x01(\x03R\x10retentionSeconds\"\x1a\n" +
	"\x18SetDefaultPolicyResponse\"\x19\n" +
	"\x17GetDefaultPolicyRequest\"\x8f\x01\n" +
	"\x18GetDefaultPolicyResponse\x12F\n" +
	"\x12default_preference\x18\x01 \x01(\x0e2\x17.scmp.v1.PullPreferenceR\x11defaultPreference\x12+\n" +
	"\x11retention_seconds\x18\x02 \x01(\x03R\x10retentionSeconds*k\n" +
	"\x0ePullPreference\x12\x1d\n" +
	"\x19PULL_PREFERENCE_IMMEDIATE\x10\x00\x12\x1e\n" +
	"\x1aPULL_PREFERENCE_ON_REQUEST\x10\x01\x12\x1a\n" +
	"\x16PULL_PREFERENCE_IGNORE\x10\x022\xdb\x03\n" +
	"\rPolicyService\x12Z\n" +
	"\x11SetPullPreference\x12!.scmp.v1.SetPullPreferenceRequest\x1a\".scmp.v1.SetPullPreferenceResponse\x12Z\n" +
	"\x11GetPullPreference\x12!.scmp.v1.GetPullPreferenceRequest\x1a\".scmp.v1.GetPullPreferenceResponse\x12`\n" +
	"\x13ListPullPreferences\x12#.scmp.v1.ListPullPreferencesRequest\x1a$.scmp.v1.ListPullPreferencesResponse\x12W\n" +
	"\x10SetDefaultPolicy\x12 .scmp.v1.SetDefaultPolicyRequest\x1a!.scmp.v1.SetDefaultPolicyResponse\x12W\n" +
	"\x10GetDefaultPolicy\x12 .scmp.v1.GetDefaultPolicyRequest\x1a!.scmp.v1.GetDefaultPolicyResponseB*Z(github.com/infodancer/scmp/proto/scmp/v1b\x06proto3"

var (
	file_scmp_v1_policy_proto_rawDescOnce sync.Once
	file_scmp_v1_policy_proto_rawDescData []byte
)

func file_scmp_v1_policy_proto_rawDescGZIP() []byte {
	file_scmp_v1_policy_proto_rawDescOnce.Do(func() {
		file_scmp_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scmp_v1_policy_proto_rawDesc), len(file_scmp_v1_policy_proto_rawDesc)))
	})
	return file_scmp_v1_policy_proto_rawDescData
}

var file_scmp_v1_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scmp_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_scmp_v1_policy_proto_goTypes = []any{
	(PullPreference)(0),                 // 0: scmp.v1.PullPreference
	(*SetPullPreferenceRequest)(nil),    // 1: scmp.v1.SetPullPreferenceRequest
	(*SetPullPreferenceResponse)(nil),   // 2: scmp.v1.SetPullPreferenceResponse
	(*GetPullPreferenceRequest)(nil),    // 3: scmp.v1.GetPullPreferenceRequest
	(*GetPullPreferenceResponse)(nil),   // 4: scmp.v1.GetPullPreferenceResponse
	(*ListPullPreferencesRequest)(nil),  // 5: scmp.v1.ListPullPreferencesRequest
	(*ListPullPreferencesResponse)(nil), // 6: scmp.v1.ListPullPreferencesResponse
	(*SetDefaultPolicyRequest)(nil),     // 7: scmp.v1.SetDefaultPolicyRequest
	(*SetDefaultPolicyResponse)(nil),    // 8: scmp.v1.SetDefaultPolicyResponse
	(*GetDefaultPolicyRequest)(nil),     // 9: scmp.v1.GetDefaultPolicyRequest
	(*GetDefaultPolicyResponse)(nil),    // 10: scmp.v1.GetDefaultPolicyResponse
}
var file_scmp_v1_policy_proto_depIdxs = []int32{
	0,  // 0: scmp.v1.SetPullPreferenceRequest.preference:type_name -> scmp.v1.PullPreference
	0,  // 1: scmp.v1.GetPullPreferenceResponse.preference:type_name -> scmp.v1.PullPreference
	4,  // 2: scmp.v1.ListPullPreferencesResponse.preferences:type_name -> scmp.v1.GetPullPreferenceResponse
	0,  // 3: scmp.v1.SetDefaultPolicyRequest.default_preference:type_name -> scmp.v1.PullPreference
	0,  // 4: scmp.v1.GetDefaultPolicyResponse.default_preference:type_name -> scmp.v1.PullPreference
	1,  // 5: scmp.v1.PolicyService.SetPullPreference:input_type -> scmp.v1.SetPullPreferenceRequest
	3,  // 6: scmp.v1.PolicyService.GetPullPreference:input_type -> scmp.v1.GetPullPreferenceRequest
	5,  // 7: scmp.v1.PolicyService.ListPullPreferences:input_type -> scmp.v1.ListPullPreferencesRequest
	7,  // 8: scmp.v1.PolicyService.SetDefaultPolicy:input_type -> scmp.v1.SetDefaultPolicyRequest
	9,  // 9: scmp.v1.PolicyService.GetDefaultPolicy:input_type -> scmp.v1.GetDefaultPolicyRequest
	2,  // 10: scmp.v1.PolicyService.SetPullPreference:output_type -> scmp.v1.SetPullPreferenceResponse
	4,  // 11: scmp.v1.PolicyService.GetPullPreference:output_type -> scmp.v1.GetPullPreferenceResponse
	6,  // 12: scmp.v1.PolicyService.ListPullPreferences:output_type -> scmp.v1.ListPullPreferencesResponse
	8,  // 13: scmp.v1.PolicyService.SetDefaultPolicy:output_type -> scmp.v1.SetDefaultPolicyResponse
	10, // 14: scmp.v1.PolicyService.GetDefaultPolicy:output_type -> scmp.v1.GetDefaultPolicyResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_scmp_v1_policy_proto_init() }
func file_scmp_v1_policy_proto_init() {
	if File_scmp_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scmp_v1_policy_proto_rawDesc), len(file_scmp_v1_policy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scmp_v1_policy_proto_goTypes,
		DependencyIndexes: file_scmp_v1_policy_proto_depIdxs,
		EnumInfos:         file_scmp_v1_policy_proto_enumTypes,
		MessageInfos:      file_scmp_v1_policy_proto_msgTypes,
	}.Build()
	File_scmp_v1_policy_proto = out.File
	file_scmp_v1_policy_proto_goTypes = nil
	file_scmp_v1_policy_proto_depIdxs = nil
}
